### ISSUE TITLE
LibreOffice dev requests changing  license to be able to integrate your extension in LibreOffice

### ISSUE THREAD

**Issue by Rosmaninho** [ACTom/lo-extension-removeduplicates#7]
https://bugs.documentfoundation.org/show_bug.cgi?id=85976

In bug 85976, Mike Kaganski wrote that GPLv3 does not allow LibreOffice to integrate the code of your extension, they are asking if you could make your extension available under a Mozilla Public License 2.0 compatible license? That way they can use your code as the starting point for their work.

> Note that any feature request having a working extension with compatible license is already an easy hack. Just use its source code as the template that provides the required logic - it uses UNO commands, which may be easily converted to a C++ code, and assign a new UNO command to that new function.
> 
> (Given that Remove Duplicates Fast is based on Remove Duplicates (https://github.com/ACTom/lo-extension-removeduplicates) which is GPLv3, which doesn't allow to use its code in LO directly because we need an MPL-compatible license, interested parties may ask the author for changed license in a github issue.)

**Comment by ACTom** [comment]
Sure, I'll change license to MPL 2.0.

**Comment by ACTom** [comment]
Changed.
